services:
  postgres:
    container_name: postgres-sql-security
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Avond778@
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: spring-security-db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:54332"
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local